config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: 'homes#top'
  get 'home/about',  to:'homes#about'
  get 'home/infomation',  to:'homes#info'
  # ログイン機能
  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # ユーザー機能
  get    '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users, only: :show
  get '/admin',  to: 'admins#top'
  # イベント機能
  resources :events, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  # Active Recordのコールバック (callback) メソッドを利用して、大文字で入力しても強制的に小文字に変換する
  before_save { self.email = email.downcase }
  validates :name, presence: true
  # 有効なメールアドレスかを判別するためにformatオプションをを用いて引数に正規表現(Regular Expression)を取る
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true,
                    format: { with: VALID_EMAIL_REGEX }
  # has_secure_passwordメソッドを記入することで、セキュアにハッシュ化したパスワードを、データベース内のpassword_digestという属性に保存できる
  # autehnticateメソッドが使用できる。また、（passwordとpassword_confirmation）というペアの属性が使えるようになり値が一致するかどうかのバリデーションが追加される
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  # before_action :logged_in,only: [:top]
  def top
    @event = Event.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # セッションを実装するには多数のメソッドを定義する必要があるため
  #セッション用ヘルパーモジュールを読み込む
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # before_action :logged_in_user, only: [:create, :index]
  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice]="You have created event successfully."
      redirect_back(fallback_location: root_path)
    else
     @events = Event.all
     render :index
    end
  end

  def index
    @events = Event.all
  end
  
  private
  
    def event_params
      params.require(:event).permit(:event_date, :address)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def info
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    # 有効なユーザーかつ正しいパスワード(true && true) == true
    if user && user.authenticate(params[:session][:password])
      flash[:notice] = "ログインしました"
      log_in user
      remember user
      redirect_to admin_path
    else
      flash.now[:alert] = "入力内容を確認してください"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Casual Aerobics!"
      redirect_to admin_path
    else
      render 'new'
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end
  # ユーザーのセッションを永続的にする
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  #現在ログイン中のユーザーを返す「 ||= 」は or equal
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end
  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  # 現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/top.html.erb
<div class = "container">
  <div class = "row">
    <div class = "mx-auto col-md-6 col-md-offset-3">
      <h1 class = "text-center">管理者画面へようこそ</h1>
      <p class = "text-center mt-3">こちらで予定を入力できます。</p>
      <%= form_with modell: @event, url: events_path, local:true do |f| %>
        <label class = "control-label mt-2">場所</label>
        <%= f.text_field :place, class: 'form-control' %>
        
        <label class = "control-label mt-2">予定日時</label>
        <%= f.datetime_field :event_date, class: 'form-control' %>
        
        <div class = "text-center mt-3">
          <%= f.submit '登録', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class = "container">
  <div class = "row">
    <div class = "mx-auto text-center col-md-6 col-md-offset-3">
      <h1>スケジュール</h1>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>場所</th>
            <th>日時</th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
            <tr>
              <td><%= event.place %></td>
              <td><%= event.event_date %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class = "about_content">
    <div class = "about_box">
        <p><strong>気軽に体を動かしてみませんか？</strong></p>
        <p class= "mt-2">運動したくてエアロビを始めたいけど、本格的なエアロビ
          についていけるか心配だなと思っていませんか？ <br>
          Casual Aerobicsでは道具やユニフォームに指定はなく、
          参加ごとの支払いのため、決まった曜日の休みをとる
          のが難しい方でも参加できます。一緒にエアロビを楽しみましょう！
        </p>
    </div>
</div>

app/views/homes/info.html.erb
<div class= "info_content">
    <div class = "info_box">
        <p><strong>Infomation</strong></p>
        <p>
          Q 料金はいくらですか？<br>
          A 料金は1参加につき800円で参加時に集金を行います。<br>
          Q 持ち物はあるますか？<br>
          A 室内用の動きやすい服装とシューズをご持参ください。
            トレーニングマットなどは初回はお貸しいたしますので
            必要に応じてご持参ください。<br>
          Q 参加したい場合はどこにいけばよいですか?<br>
          A "こちら"のページに来月のスケジュールの記載があります。
            体育館の都合などにより、変更の可能性があります。
            体育館の受付で案内が受けれますが、分からなければ
            事前にご連絡ください。<br>
          Q 見学は可能ですか？<br>
          A 可能ですが体育館により見学のしやすさが異なります。
            もし興味を持っていただけましたらご連絡ください。
        </p>
        <p>連絡先:　casualaerobics@mail</p>
    </div>
</div>

app/views/homes/place.html.erb
<!--来週の開催場所を表示-->
<!--管理者側で日時と開催場所を投稿してそのデータを取り出して表示する。-->
<!--スケジュールはカレンダーを用いてクリックすると詳細表示。-->

app/views/homes/top.html.erb
<div class = "home_content">
  <div class = "top_box">
    Welcome to <br>
    Casual Aerobics !
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <ul class = "footer-text">
    <li>© casual_aerobics</li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/"><span>Casual Aerobics</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <%# if user_signed_in? %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link text-light" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", home_about_path, class: "nav-link text-light" %>
          </li>
          <li class="nav-item">
            <%= link_to "Info", home_infomation_path, class: "nav-link text-light" %>
          </li>
        <%# else %>
          <!--          <li class="nav-item">-->
            <%#= link_to "Home", root_path, class: "nav-link text-light" %>
          <!--</li>-->
          <!--<li class="nav-item">-->
            <%#= link_to "About", home_about_path, class: "nav-link text-light" %>
          <!--</li>-->
          <!--<li class="nav-item">-->
            <%#= link_to "Info", home_infomation_path, class: "nav-link text-light" %>
          <!--</li>-->
          <!--<li class="nav-item">-->
            <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link text-light" %>
          <!--</li>-->
        <%# end %>
        </ul>
      </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AerobicsSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <%= render "layouts/header"%>
      <main>
        <%= yield %>
      </main>
        <%= render "layouts/footer"%>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <!--pluralizeと書くことで"0 errors", "1 erros", "2 errors"と繰り返さなくなる-->
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <!--errors.full_messagesオブジェクトは以下の配列を持つ
      ["Email is invalid", "Password is too short (minimum is 6 characters)"]-->
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<div class = "container">
  <% provide(:title, 'Sign up') %>
  
  <div class="row">
    <div class="mx-auto col-md-6 col-md-offset-3">
      <h1 class = "text-center">サインアップ</h1>
  
      <%= form_for(@user, url: signup_path) do |f| %>
        <%= render 'shared/error_messages' %>
  
        <%= f.label :名前 %>
        <%= f.text_field :name, class: 'form-control mt-2' %>
  
        <%= f.label :メールアドレス %>
        <%= f.email_field :email, class: 'form-control mt-2' %>
  
        <%= f.label :パスワード %>
        <%= f.password_field :password, class: 'form-control mt-2' %>
  
        <%= f.label :password_confirmation, "パスワード確認用" %>
        <%= f.password_field :password_confirmation, class: 'form-control mt-2' %>
        <div class="text-center">
          <%= f.submit "作成！", class: "btn btn-primary mt-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>